# Generated by Django 5.2.8 on 2026-01-01 22:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venda',
            new_name='DatasCSV',
        ),
    ]
