# Generated by Django 5.2.8 on 2026-01-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_venda_datascsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasCSV',
        ),
    ]
